apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: catalog

resources:
  - ../../base

images:
  - name: shopstack-catalog
    newName: 770132776547.dkr.ecr.us-east-1.amazonaws.com/shopstack-catalog
    newTag: "latest"

patches:
  - path: patch-image-pull-secret.yaml
    target:
      kind: Deployment
      name: catalog
