apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/example-app
namePrefix: prod-
labels:
  - pairs:
      environment: production
replicas:
  - name: example-app
    count: 3
