apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/example-app
namePrefix: staging-
labels:
  - pairs:
      environment: staging
replicas:
  - name: example-app
    count: 2
