apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/example-app
namePrefix: dev-
labels:
  - pairs:
      environment: dev
replicas:
  - name: example-app
    count: 1
